# Generated by Django 4.1.2 on 2022-11-01 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('damage', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('1', 'Wizard'), ('2', 'Warrior'), ('3', 'Archer')], max_length=20)),
                ('inventory', models.ManyToManyField(related_name='weapons', to='inventories.inventory')),
            ],
        ),
    ]
