# Generated by Django 4.1.2 on 2022-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("Warrior", "Warrior"),
                    ("Wizard", "Wizard"),
                    ("Archer", "Archer"),
                ],
                max_length=15,
                unique=True,
            ),
        ),
    ]
