# Generated by Django 4.1.2 on 2022-11-01 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strength', models.PositiveIntegerField(default=1)),
                ('agility', models.PositiveIntegerField(default=1)),
                ('intelligence', models.PositiveIntegerField(default=1)),
                ('endurance', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
